### ISSUE TITLE
zip object is not JSON serializable when generating graph

### ISSUE THREAD

**Issue by timothyleung** [agiliq/django-graphos#36] opened 2016-05-06 06:24 UTC
By following the tutorial, I have the following set up 

```
# view 
def salesboard(request):
    # render the graph here
    data =  [
            ['Year', 'Sales', 'Expenses'],
            [2004, 1000, 400],
            [2005, 1170, 460],
            [2006, 660, 1120],
            [2007, 1030, 540]
        ]
    chart = flot.LineChart(SimpleDataSource(data=data), html_id="Line Chart")
    return render_to_response('scoreboard.html', {'chart':chart})
```
Template 
`{{ chart.as_html }}`

Error 
```
Error during template rendering

In template C:\Users\TIMLEU~1\Desktop\SYSTEM~1\sp-venv\lib\site-packages\graphos\templates\graphos\flot.html, error at line 4
<zip object at 0x00000052AAC8D448> is not JSON serializable
1   <div id="{{ chart.html_id }}" style="width:{{ chart.width }}px;height:{{ chart.height }}px;"></div>
2   <script type="text/javascript">
3   $(function () {
4       data{{ chart.html_id }} = {{ chart.get_series_objects_json|safe }}
5       $plot{{ chart.html_id }} = $.plot(
6           $("#{{ chart.html_id }}"),
7           data{{ chart.html_id }},
8           {{ chart.get_options_json|safe }}
9       );
10  });
11  </script>
```

**Comment by e78908b943c8** [comment] 2016-05-14 06:22
I'm having the same issue with python3.4
I did some digging and found that `get_serieses` in `BaseFlowChart` is storing the result of `zip` which then gets json serialized.
![image](https://cloud.githubusercontent.com/assets/7596842/15266578/e8684e16-19e4-11e6-979a-02f2d1239095.png)
The problem is that the `zip` method in python 2 returns a list of tuples whereas in python 3 a `zip` object is returned.
The `zip` should be converted to a `list` as such.
![image](https://cloud.githubusercontent.com/assets/7596842/15266654/869abf86-19e7-11e6-8589-63d53b6bb793.png)

**Comment by timothyleung** [comment] 2016-05-16 00:39
Yup Thats what I did to fix it as well! Feel like we should create a pull request for this

**Comment by ModusVivendi** [comment] 2016-05-17 14:44
Pull request https://github.com/agiliq/django-graphos/pull/32 takes care of this.

**Comment by akshar-raaj** [comment] 2016-07-20 12:41
@timothyleung @e78908b943c8 @ModusVivendi @sheepeatingtaz PR https://github.com/agiliq/django-graphos/pull/32 has been merged and updated code has been uploaded to Pypi. With recent "pip install django-graphos" this issue should be resolved.

**Closed by akshar-raaj** 2016-07-20 12:41 UTC
Labels: bug

**Comment by dockerfile57** [comment] 2025-02-01 00:09
> [@timothyleung](https://github.com/timothyleung) [@e78908b943c8](https://github.com/e78908b943c8) [@ModusVivendi](https://github.com/ModusVivendi) [@sheepeatingtaz](https://github.com/sheepeatingtaz) PR [#32](https://github.com/agiliq/django-graphos/pull/32) has been merged and updated code has been uploaded to Pypi. With recent "pip install django-graphos" this issue should be resolved.





https://pythondev.space/questions/pythons-zip-function-does-not-return-a-json-serializable-object
